<a href="https://colab.research.google.com/github/LeeSeungwon89/Python_for_Data_Analytics_Science/blob/main/2.%20%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%A5%BC%20%EB%8B%A4%EB%A3%A8%EA%B8%B0%20%EC%9C%84%ED%95%9C%20%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%ED%8C%A8%ED%82%A4%EC%A7%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Numpy**

넘파이는 데이터를 다루는 데 필수적인 패키지입니다. 과학적인 연산을 빠르고 쉽게 해줍니다. 아래에는 몇 가지 내용만 정리하겠습니다. 이외 구체적인 정보는 [넘파이 홈페이지](https://www.numpy.org)에 정리되어 있습니다.

## **1.1. 배열 만들기**

배열을 만드는 방법은 여러가지가 있습니다. 

아래에서 예시로 설명하겠습니다. 먼저 시퀀스 데이터를 인자로 받고 배열 객체를 생성하는 방법입니다.

In [7]:
import numpy as np
# 튜플도 가능하지만 주로 리스트를 사용합니다.
# 정수만으로 구성된 리스트입니다.
list_int = [0, 1, 2, 3, 4]
np_int = np.array(list_int)
print(np_int)
np_int

[0 1 2 3 4]


array([0, 1, 2, 3, 4])

배열 속성을 확인합니다.

In [8]:
np_int.dtype

dtype('int64')

정수와 실수를 함께 포함시켜서 만들겠습니다. 이렇게 하면 모든 원소를 실수 형태로 출력합니다.

In [9]:
list_combi = [0, 1.2, 3, 4.56, 7]
np_combi = np.array(list_combi)
np_combi

array([0.  , 1.2 , 3.  , 4.56, 7.  ])

배열 속성을 확인합니다.

In [10]:
np_combi.dtype

dtype('float64')

문자를 함께 포함시키겠습니다. 이렇게 하면 모든 원소를 문자로 간주하게 됩니다.

In [11]:
list_str = [0, '일', 2.3, '사']
np_str = np.array(list_str)
np_str

array(['0', '일', '2.3', '사'], dtype='<U21')

배열 속성을 확인합니다. '<U21'는 유니코드 문자열을 의미합니다. 여기서 '21'은 문자 수가 최대 21개라는 점을 의미합니다.

In [12]:
np_str.dtype

dtype('<U21')

`np.array(리스트)` 형식으로 바로 배열 객체를 만들 수도 있습니다.

In [13]:
np_direct1 = np.array([0, 1, 2, 3, 4])
np_direct1

array([0, 1, 2, 3, 4])

In [14]:
np_direct2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
np_direct2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

범위를 지정해서 배열을 만들 수 있습니다. 파이썬 `range()` 함수와 유사하게 넘파이는 `arange()` 함수를 사용합니다.

In [15]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`arange()` 함수에 `reshape()` 함수를 더하면 행렬 형태로 변경할 수 있습니다.

In [18]:
np.arange(8).reshape(4, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

배열 형태를 확인하겠습니다. 참고로 1차원 배열은 `(원소 개수,)` 형태로 출력됩니다. 예컨대 원소 개수가 34개라면 `(34,)`로 출력됩니다.

In [19]:
np_reshape = np.arange(8).reshape(4, 2)
np_reshape.shape

(4, 2)

`linspace()` 함수를 사용하면 지정한 데이터 개수에 따라 배열을 만듭니다. 0부터 10까지 20개만큼 데이터를 만들겠습니다.

In [20]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

`zeros()` 함수는 0으로만 이루어진 배열을 만듭니다. `ones()` 함수는 1로만 이루어진 배열을 만듭니다. 사용법은 동일합니다.

In [21]:
zeros_1 = np.zeros(5)
print(zeros_1)
print()
# 2차원 배열을 만들려면 괄호로 한 번 더 묶어야 합니다.
ones_2 = np.ones((5, 2))
print(ones_2)

[0. 0. 0. 0. 0.]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


`eye()` 함수는 단위행렬(Identity matrix)을 만듭니다. 

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

`rand()` 함수와 `randint()` 함수는 각각 실수 난수와 정수 난수를 생성합니다. 

In [23]:
rand1 = np.random.rand()
print(rand1)
print()
# 2 x 4 배열을 생성합니다.
rand2 = np.random.rand(2, 4)
print(rand2)
print()
# 3차원 배열을 생성합니다.
rand3 = np.random.rand(2, 4, 6)
print(rand3)

0.27943185322877495

[[0.04669227 0.30817079 0.32909436 0.51292183]
 [0.36114944 0.40957512 0.08951693 0.4197528 ]]

[[[0.89819608 0.3041051  0.72794729 0.32042446 0.04412302 0.46372721]
  [0.64422346 0.15209883 0.09061946 0.83386941 0.81097201 0.05546235]
  [0.14616913 0.42035443 0.80827199 0.52696646 0.29317509 0.59240928]
  [0.53250265 0.32324904 0.30953117 0.63342033 0.33917346 0.99635982]]

 [[0.50676606 0.15085427 0.73542097 0.98219033 0.55153439 0.14314686]
  [0.00479392 0.93442316 0.3472801  0.66037115 0.78617497 0.65211656]
  [0.94383901 0.22568341 0.21298065 0.64414264 0.72890584 0.28894747]
  [0.56855711 0.67916767 0.87887487 0.43187963 0.27233403 0.11225205]]]


In [24]:
# 5~10 사이의 정수 난수를 생성합니다.
randint1 = np.random.randint(5, 10)
print(randint1)
print()
# 0 ~ 10 사이의 정수 난수를 2 x 5 배열로 생성합니다.
randint2 = np.random.randint(10, size=(2, 5))
print(randint2)
print()
# 0 ~ 12 사이의 정수 난수를 3차원 배열로 생성합니다.
randint3 = np.random.randint(12, size=(3, 2, 5))
print(randint3)

9

[[0 9 9 0 7]
 [5 3 4 8 0]]

[[[ 0  6 10  5 10]
  [11  6  9  0  9]]

 [[ 9  3  9  7  1]
  [ 8  8  2  2  6]]

 [[ 7  8  2 10 11]
  [ 3  7 11  6  1]]]


## **1.2. 배열 타입 변환하기**

넘파이 데이터의 형식은 아래와 같습니다.

- 'i': 기호를 가진 정수(signed integer)

- 'u': 기호가 없는 정수(unsigned integer)

- 'f': 실수(floating-point)

- 'c': 복소수(complex-floating point)

- 'b': 불(bool)

- 'O': 파이썬 객체(object)

- 'U': 유니코드(unicode)

- 'S' or 'a': 바이트 문자열(string)

- 'M': 날짜(datetime)

`astype()` 함수를 사용하여 배열 타입(형)을 바꿀 수 있습니다. `astype()` 함수에 인자로 `int`(정수형), `float`(실수형), `str`(문자형) 중에 하나를 넣고 배열 형을 변환합니다.

In [25]:
np_str = np.array(['0.1', '2', '3.45', '6.7'])
print(f'np_str의 타입은 {np_str.dtype}')
# 실수 타입으로 변환합니다.
np_astype_float = np_str.astype(float)
print(f'np_astype_float의 타입은 {np_astype_float.dtype}')
# 정수 타입으로 변환합니다. 
np_astype_int = np_astype_float.astype(int)
print(f'np_astype_int의 타입은 {np_astype_int.dtype}, 원소는 {np_astype_int}')

np_str의 타입은 <U4
np_astype_float의 타입은 float64
np_astype_int의 타입은 int64, 원소는 [0 2 3 6]


## **1.3. 배열 연산하기**

통계에 활용하는 여러 함수가 있습니다. 아래는 함수 목록입니다.

- `sum()`: 합계

- `mean()`: 평균

- `std()`: 표준 편차

- `var()`: 분산

- `max()`: 최댓값

- `min()`: 최솟값

- `cumsum()`: 누적합

- `cumprod()`: 누적곱

배열을 생성하고 예시를 들겠습니다.

In [26]:
arr_cal = np.arange(7)
print(f'arr_cal: {arr_cal}')
print(f'sum(): {arr_cal.sum()}')
print(f'mean(): {arr_cal.mean()}')
print(f'std(): {arr_cal.std()}')
print(f'var(): {arr_cal.var()}')
print(f'max(): {arr_cal.max()}')
print(f'min(): {arr_cal.min()}')
print(f'cumsum(): {arr_cal.cumsum()}')
print(f'sumprod(): {arr_cal.cumprod()}')

arr_cal: [0 1 2 3 4 5 6]
sum(): 21
mean(): 3.0
std(): 2.0
var(): 4.0
max(): 6
min(): 0
cumsum(): [ 0  1  3  6 10 15 21]
sumprod(): [0 0 0 0 0 0 0]


선형 대수를 위한 행렬 연산을 수행하는 함수도 있습니다. 아래는 함수 목록입니다.

- `dot()`: 행렬곱(matrix product)
- `transpose()`: 전치 행렬(transpose matrix)
- `linalg.inv()`: 역행렬(inverse matrix)
- `linalg.det()`: 행렬식(determinant)

2차원 배열을 생성하고 함수를 사용하겠습니다.

In [27]:
matrix1 = np.array([0, 1, 2, 3]).reshape(2, 2)
matrix2 = np.array([1, 2, 3, 4]).reshape(2, 2)
print('matrix1:')
print(matrix1)
print('matrix2:')
print(matrix2)

matrix1:
[[0 1]
 [2 3]]
matrix2:
[[1 2]
 [3 4]]


`dot()` 함수로 행렬곱을 구하겠습니다. 두 형식으로 쓸 수 있습니다.

In [28]:
print('matrix1:')
print(matrix1)
print('matrix1.dot(matrix2):')
print(matrix1.dot(matrix2))
print('np.dot(matrix1, matrix2):')
print(np.dot(matrix1, matrix2))

matrix1:
[[0 1]
 [2 3]]
matrix1.dot(matrix2):
[[ 3  4]
 [11 16]]
np.dot(matrix1, matrix2):
[[ 3  4]
 [11 16]]


`transpose()` 함수로 전치 행렬을 만들겠습니다. 두 형식으로 쓸 수 있습니다.

In [29]:
print('matrix1:')
print(matrix1)
print('matrix1.transpose():')
print(matrix1.transpose())
print('np.transpose(matrix1):')
print(np.transpose(matrix1))

matrix1:
[[0 1]
 [2 3]]
matrix1.transpose():
[[0 2]
 [1 3]]
np.transpose(matrix1):
[[0 2]
 [1 3]]


`linalg.inv()` 함수로 역행렬을 구하겠습니다.

In [30]:
print('matrix1:')
print(matrix1)
print('np.linalg.inv(matrix1):')
print(np.linalg.inv(matrix1))

matrix1:
[[0 1]
 [2 3]]
np.linalg.inv(matrix1):
[[-1.5  0.5]
 [ 1.   0. ]]


`linalg.det()` 함수로 행렬식을 구하겠습니다.

In [31]:
print('matrix1:')
print(matrix1)
print('np.linalg.det(matrix1):')
print(np.linalg.det(matrix1))

matrix1:
[[0 1]
 [2 3]]
np.linalg.det(matrix1):
-2.0


## **1.4. 배열 인덱싱 하기**

배열을 인덱싱 할 때 조건에 부합하는 원소를 인덱싱 할 수 있습니다.

In [32]:
list_indexing = np.arange(30)
print(f'list_indexing > 15: {list_indexing[list_indexing > 15]}')
print(f'list_indexing / 5 == 5: {list_indexing[list_indexing / 5 == 5]}')

list_indexing > 15: [16 17 18 19 20 21 22 23 24 25 26 27 28 29]
list_indexing / 5 == 5: [25]


## **1.5. 배열 슬라이싱 하기**

배열 슬라이싱은 간혹 끝 위치 숫자가 헷갈릴 수 있습니다. 반드시 끝 위치-1까지 슬라이싱 한다는 점을 유의해야 합니다.

팁이라면 '끝 위치'에서 '시작 위치'를 뺀 값을 슬라이싱 할 개수로 여기고, 시작 위치에서 그 개수만큼 배열 슬라이싱 한다고 생각하면 수월합니다.

아래 코드를 토대로 예시합니다.

In [33]:
example_slicing = np.array([0, 3, 6, 2, 10, 66, 21])
example_slicing[2:5]

array([ 6,  2, 10])

2에서 4까지 원소가 반환됐습니다. 슬라이싱을 2:5만큼 했으므로 5(끝 위치) - 2(시작 위치) = 3(반환 개수)입니다. 2의 위치의 원소인 6을 포함하여 3개가 차례로 반환된 것입니다. 

# **2. Pandas**

판다스는 데이터를 쉽게 처리할 수 있도록 특화된 라이브러리입니다. 자세한 내용은 [판다스 홈페이지](https://pandas.pydata.org)에 정리되어 있습니다.

## **2.1. 데이터 구조 만들기**

`Series()` 메서드를 사용하여 라벨이 있는 1차원 데이터를 생성할 수 있습니다. 이 데이터의 형식은 'Series'입니다.

아래는 이에 대한 예시입니다. 숫자, 문자열, 공백을 함께 포함시키겠습니다. 여기서 공백은 넘파이의 공백을 나타내는 `np.nan` 형태로 취합니다. 

In [34]:
import numpy as np
import pandas as pd

# 대부분 리스트를 사용합니다. 
series1 = pd.Series([11, 22, 'a', 'b', np.nan, 33])
series1

0     11
1     22
2      a
3      b
4    NaN
5     33
dtype: object

첫째 열의 라벨은 'index'입니다. 0부터 오름차순으로 부여되며 데이터의 순서를 의미합니다. 둘째 열은 'values'입니다. 데이터의 값을 의미합니다.

이 데이터의 열을 따로 가져올 수 있습니다. 아래에서 예시하겠습니다.

In [35]:
print(series1.index)
# 배열 형식을 살피기 위해 `print()` 함수를 사용하지 않습니다.
series1.values

RangeIndex(start=0, stop=6, step=1)


array([11, 22, 'a', 'b', nan, 33], dtype=object)

배열 형식은 넘파이입니다.

위에서는 인덱스가 0부터 오름차순으로 부여됐습니다. 원하는 인덱스를 따로 지정하려면 `index=리스트명`을 `Series()` 메서드에 전달합니다.

In [36]:
index1 = ['그저께', '어제', '오늘', '내일', '내일모레']
series2 = pd.Series([50, 100, 20, np.nan, '휴식'], index=index1)
series2

그저께      50
어제      100
오늘       20
내일      NaN
내일모레     휴식
dtype: object

딕셔너리 형식으로 인덱스(index)와 데이터(values)를 한 번에 입력할 수도 있습니다.

In [37]:
series3 = pd.Series({'자전거': 150, '신발': 20, '바지':10, '헬멧': 15})
series3

자전거    150
신발      20
바지      10
헬멧      15
dtype: int64

`date_range()` 메서드는 지정한 기간만큼 날짜를 생성합니다. 날짜 형식은 'yyyy-mm-dd'로 지정하겠습니다. 추가로 'yyyy.mm.dd', 'yyyy/mm/dd', 'mm-dd-yyyy', 'mm.dd.yyyy', 'mm/dd/yyyy' 모두 가능합니다. 단 생성되는 날짜의 형식은 모두 'yyyy-mm-dd'입니다.

In [38]:
print(pd.date_range(start='2021-10-04', end='2021-10-09'))
# `periods` 매개변수에 값을 지정하면 기간만큼 날짜를 생성합니다.
print(pd.date_range(start='2021-10-04', periods=6))

DatetimeIndex(['2021-10-04', '2021-10-05', '2021-10-06', '2021-10-07',
               '2021-10-08', '2021-10-09'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2021-10-04', '2021-10-05', '2021-10-06', '2021-10-07',
               '2021-10-08', '2021-10-09'],
              dtype='datetime64[ns]', freq='D')


`date_range()` 메서드의 매개변수인 `freq`에 값을 지정하면 원하는 주기로 날짜를 생성할 수 있습니다. 아래는 그 값의 목록입니다.

- `D`: 하루(Day) 주기입니다. 이틀 주기로 생성하려면 `2D`입니다.

- `B`: 업무일(Business day, 월~금) 주기입니다. `3B`도 가능합니다.

- `W`: 일주일(Week) 주기입니다. 일요일 시작은 `W` 또는 `W-SUN`이며, 월요일 시작은 `W-MON`입니다.

- `M`: 월말(Month end) 날짜 주기입니다. 한 달 주기는 `M`, 네 달 주기는 `4M`입니다.

- `BM`: 업무 월말(Business month end) 날짜 주기입니다. `2BM`도 가능합니다.

- `MS`: 월초(Month start) 날짜 주기입니다. 위 인자들처럼 `MS` 앞에 숫자를 붙일 수 있습니다.

- `BMS`: 업무 월초(Business month start) 날짜 주기입니다. 똑같이 숫자를 붙일 수 있습니다. 이하 인자들도 같습니다.

- `Q`: 분기말(Quater end) 날짜 주기입니다.

- `BQ`: 업무 분기말(Business quater end) 날짜 주기입니다. 

- `QS`: 분기초(Quater start) 날짜 주기입니다. 

- `BQS`: 업무 분기초(Business quater start) 날짜 주기입니다.

- `A`: 연말(Year end) 날짜 주기입니다.

- `BA`: 업무 연말(Business year end) 날짜 주기입니다.

- `AS`: 연초(Year start) 날짜 주기입니다.

- `BAS`: 업무 연초(Business year start) 날짜 주기입니다.

- `H`: 시간(Hour) 주기입니다.

- `BH`: 업무 시간(Business hour) 주기입니다. 9:00 ~ 17:00를 기준으로 갖습니다.

- `T`, `min`: 분(Minute) 주기입니다.

- `S`: 초(Second) 주기입니다.

아래에 몇 가지 예시를 들겠습니다. 먼저 다섯 날을 4일 간격으로 생성합니다.

In [39]:
pd.date_range(start='2021-10-04', periods=5, freq='4D')

DatetimeIndex(['2021-10-04', '2021-10-08', '2021-10-12', '2021-10-16',
               '2021-10-20'],
              dtype='datetime64[ns]', freq='4D')

3주일씩 증가시키겠습니다.

In [40]:
pd.date_range(start='2021-10-04', periods=5, freq='3W')

DatetimeIndex(['2021-10-10', '2021-10-31', '2021-11-21', '2021-12-12',
               '2022-01-02'],
              dtype='datetime64[ns]', freq='3W-SUN')

업무일 월초 날짜를 생성하겠습니다.

In [41]:
pd.date_range(start='2021-10-04', periods=5, freq='BMS')

DatetimeIndex(['2021-11-01', '2021-12-01', '2022-01-03', '2022-02-01',
               '2022-03-01'],
              dtype='datetime64[ns]', freq='BMS')

업무일 월말 날짜를 두 달 간격으로 생성하겠습니다.

In [42]:
pd.date_range(start='2021-10-04', periods=5, freq='2BM')

DatetimeIndex(['2021-10-29', '2021-12-31', '2022-02-28', '2022-04-29',
               '2022-06-30'],
              dtype='datetime64[ns]', freq='2BM')

업무일 분기초 날짜를 생성하겠습니다. 

In [43]:
pd.date_range(start='2021-10-04', periods=5, freq='BQS')

DatetimeIndex(['2022-01-03', '2022-04-01', '2022-07-01', '2022-10-03',
               '2023-01-02'],
              dtype='datetime64[ns]', freq='BQS-JAN')

내용을 응용하여 시리즈를 생성하겠습니다.

In [44]:
date_index = pd.date_range(start='2021-06-01', periods=5, freq='M')
num_values = [100, 241, 213, 152, 656]
pd.Series(num_values, index=date_index)

2021-06-30    100
2021-07-31    241
2021-08-31    213
2021-09-30    152
2021-10-31    656
Freq: M, dtype: int64

위에서는 `Series()` 메서드를 사용해서 1차원 데이터 구조를 만들었습니다. `DataFrame()` 메서드는 2차원 데이터 구조를 만듭니다. 이 메서드도 첫 열에 인덱스를 숫자형 라벨로 자동으로 부여하지만, 차이점이라면 칼럼도 숫자형 라벨로 자동으로 부여합니다. 물론 인덱스와 칼럼 모두 라벨을 직접 지정할 수 있습니다.

먼저 간단하게 예시하겠습니다.

In [45]:
# 데이터 프레임을 생성하려면 2차원 리스트를 사용해야 합니다.
pd.DataFrame([[11, 22, 33, 44], [55, 66, 77, 88]])

0   1   2   3
0  11  22  33  44
1  55  66  77  88

넘파이 배열로도 values를 전달할 수 있습니다.

In [46]:
np_nums = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
pd.DataFrame(np_nums)

0   1   2
0  11  22  33
1  44  55  66
2  77  88  99

인덱스와 칼럼명까지 함께 지정하여 데이터 프레임을 만들겠습니다.

In [47]:
np_nums1 = np.array([[42, 27, 54], [36, 75, 97], [33, 15, 26]])
date_index = pd.date_range('2021-10-09', periods=3, freq='3H')
col_list = ['사과', '배', '포도']
pd.DataFrame(np_nums1, index=date_index, columns=col_list)

사과   배  포도
2021-10-09 00:00:00  42  27  54
2021-10-09 03:00:00  36  75  97
2021-10-09 06:00:00  33  15  26

딕셔너리로 데이터 프레임을 만들겠습니다.

In [48]:
dic_data1 = {'입대일': ['2012-09-12', '2012-09-12', '2012-09-12', '2012-09-12'],
            '군번': [20129948, 20129593, 20129302, 20129352],
            '이름': ['이승민', '김대철', '장비호', '이진해'],
            '보직': [20, 30, 10, 30]}
pd.DataFrame(dic_data1)

입대일        군번   이름  보직
0  2012-09-12  20129948  이승민  20
1  2012-09-12  20129593  김대철  30
2  2012-09-12  20129302  장비호  10
3  2012-09-12  20129352  이진해  30

칼럼을 재정렬하겠습니다.

In [49]:
pd.DataFrame(dic_data1, columns=['군번', '입대일', '이름', '보직'])

군번         입대일   이름  보직
0  20129948  2012-09-12  이승민  20
1  20129593  2012-09-12  김대철  30
2  20129302  2012-09-12  장비호  10
3  20129352  2012-09-12  이진해  30

## **2.2. 데이터 연산하기**

시리즈끼리 데이터를 연산할 수 있습니다. 단 연산할 대상이 없는 경우는 'NaN'으로 처리됩니다.

In [50]:
series4 = pd.Series(['영', 1, 2, 3])
series5 = pd.Series([4, 5, 6, 7, 8])
series4 * series5

0    영영영영
1       5
2      12
3      21
4     NaN
dtype: object

데이터 프레임끼리도 연산이 가능합니다. 시리즈처럼 연산이 불가능한 경우는 'NaN'으로 처리됩니다.

In [51]:
dic_data2 = {'a': [0, 1, 2],
             'b': [3, 4, 5],
             'c': [6, 7, 8]}
dataframe1 = pd.DataFrame(dic_data2)

dic_data3 = {'a': [10, 20, 30, 40],
             'b': [50, 60, 70, 80],
             'c': [90, 100, 110, 120]}
dataframe2 = pd.DataFrame(dic_data3)
dataframe1 + dataframe2

a     b      c
0  10.0  53.0   96.0
1  21.0  64.0  107.0
2  32.0  75.0  118.0
3   NaN   NaN    NaN

넘파이와 비슷하게 통계 함수를 사용할 수 있습니다. 아래는 판다스에서 사용할 수 있는 몇 가지 함수 목록입니다.

- `sum()`: 합계

- `mean()`: 평균

- `std()`: 표준 편차

- `var()`: 분산

- `max()`: 최댓값

- `min()`: 최솟값

- `cumsum()`: 누적합

- `cumprod()`: 누적곱

- `median()`: 중간값

- `corr()`: 상관계수

- `describe()`: 원소 개수, 평균, 표준 편차, 최솟값, 최댓값. 매개변수를 `include=all`로 지정하면 고유값 개수, 최빈값, 빈도수를 추가합니다.

`describe()` 함수에 대한 예시를 들겠습니다.

In [52]:
dic_data4 = {'사과': [332, 392, 391, 295, 374],
             '배': [102, 99, 80, 30, 143],
             '포도': [402, 497, 306, 681, 573]}
col_list1 = ['포도', '사과', '배']
index2 = ['4월', '5월', '6월', '7월', '8월']

dataframe3 = pd.DataFrame(dic_data4, columns=col_list1, index=index2)

print(dataframe3)
print()

print('평균')
print(dataframe3.mean())
print()

# `display` 메서드를 사용하면 데이터 프레임 형태로 출력합니다.
display(dataframe3.describe())

     포도   사과    배
4월  402  332  102
5월  497  392   99
6월  306  391   80
7월  681  295   30
8월  573  374  143

평균
포도    491.8
사과    356.8
배      90.8
dtype: float64



포도         사과           배
count    5.000000    5.00000    5.000000
mean   491.800000  356.80000   90.800000
std    145.776198   42.24571   41.020726
min    306.000000  295.00000   30.000000
25%    402.000000  332.00000   80.000000
50%    497.000000  374.00000   99.000000
75%    573.000000  391.00000  102.000000
max    681.000000  392.00000  143.000000

## **2.3. 데이터 선택하기**

먼저 데이터 프레임을 이전보다 크게 생성하겠습니다.

In [53]:
dic_data5 = {'사과': [332, 392, 391, 295, 374, 333, 282],
             '배': [102, 99, 80, 30, 143, 26, 21],
             '포도': [402, 497, 306, 681, 573, 777, 821],
             '딸기': [756, 741, 794, 772, 703, np.nan, np.nan],
             '복숭아': [32, 70, 26, 154, 201, np.nan, np.nan]}
col_list2 = ['배', '사과', '포도', '딸기', '복숭아']
index3 = ['4월', '5월', '6월', '7월', '8월', '9월', '10월']

dataframe4 = pd.DataFrame(dic_data5, columns=col_list2, index=index3)
display(dataframe4)
print()

print(dataframe4.index)
print()

print(dataframe4.columns)
print()

print(dataframe4.values)

배   사과   포도     딸기    복숭아
4월   102  332  402  756.0   32.0
5월    99  392  497  741.0   70.0
6월    80  391  306  794.0   26.0
7월    30  295  681  772.0  154.0
8월   143  374  573  703.0  201.0
9월    26  333  777    NaN    NaN
10월   21  282  821    NaN    NaN


Index(['4월', '5월', '6월', '7월', '8월', '9월', '10월'], dtype='object')

Index(['배', '사과', '포도', '딸기', '복숭아'], dtype='object')

[[102. 332. 402. 756.  32.]
 [ 99. 392. 497. 741.  70.]
 [ 80. 391. 306. 794.  26.]
 [ 30. 295. 681. 772. 154.]
 [143. 374. 573. 703. 201.]
 [ 26. 333. 777.  nan  nan]
 [ 21. 282. 821.  nan  nan]]


행과 열을 바꾸려면 `T` 메서드를 사용합니다. 물론 영구적으로 바뀌지 않고 메서드를 사용할 때만 바뀝니다. 객체에 넘겨주면 전치된 데이터 프레임을 유지할 수 있습니다.

In [54]:
dataframe4.T

4월     5월     6월     7월     8월     9월    10월
배    102.0   99.0   80.0   30.0  143.0   26.0   21.0
사과   332.0  392.0  391.0  295.0  374.0  333.0  282.0
포도   402.0  497.0  306.0  681.0  573.0  777.0  821.0
딸기   756.0  741.0  794.0  772.0  703.0    NaN    NaN
복숭아   32.0   70.0   26.0  154.0  201.0    NaN    NaN

전체 데이터를 모두 선택하지 않고 앞과 뒤의 일부 데이터만 선택하려면 각각 `head()` 메서드와 `tail()` 메서드를 사용합니다. 괄호 안에 숫자를 인자로 지정하면 데이터가 숫자만큼 출력됩니다. 기본값은 `5`입니다.

In [55]:
dataframe4.head()

배   사과   포도     딸기    복숭아
4월  102  332  402  756.0   32.0
5월   99  392  497  741.0   70.0
6월   80  391  306  794.0   26.0
7월   30  295  681  772.0  154.0
8월  143  374  573  703.0  201.0

In [56]:
dataframe4.tail(3)

배   사과   포도     딸기    복숭아
8월   143  374  573  703.0  201.0
9월    26  333  777    NaN    NaN
10월   21  282  821    NaN    NaN

원하는 행을 출력하려면 슬라이싱을 사용합니다.

In [57]:
dataframe4[2:6]

배   사과   포도     딸기    복숭아
6월   80  391  306  794.0   26.0
7월   30  295  681  772.0  154.0
8월  143  374  573  703.0  201.0
9월   26  333  777    NaN    NaN

`loc[]` 메서드에 인덱스를 지정해서 해당하는 행만 가져올 수 있습니다.

In [58]:
dataframe4.loc['8월']

배      143.0
사과     374.0
포도     573.0
딸기     703.0
복숭아    201.0
Name: 8월, dtype: float64

`loc[]` 메서드로 인덱스를 슬라이싱 할 수도 있습니다. '8월'부터 마지막까지 가져오겠습니다.

In [59]:
dataframe4.loc['8월':]

배   사과   포도     딸기    복숭아
8월   143  374  573  703.0  201.0
9월    26  333  777    NaN    NaN
10월   21  282  821    NaN    NaN

`loc[]` 메서드를 사용해서 두 가지 형식으로 원하는 값을 가져오겠습니다. '딸기' 열의 '7월' 값을 가져오겠습니다.

In [60]:
dataframe4.loc['7월']['딸기']

772.0

In [61]:
dataframe4.loc['7월', '딸기']

772.0

열을 하나만 가져오겠습니다. 참고로 인덱스를 가져오려면 반드시 `loc[]` 메서드를 사용해야 합니다.

In [62]:
dataframe4['딸기']

4월     756.0
5월     741.0
6월     794.0
7월     772.0
8월     703.0
9월       NaN
10월      NaN
Name: 딸기, dtype: float64

열을 두 개 가져오겠습니다. 다수의 원소는 리스트로 한 번 더 묶어야 합니다.

In [63]:
dataframe4[['딸기', '포도']]

딸기   포도
4월   756.0  402
5월   741.0  497
6월   794.0  306
7월   772.0  681
8월   703.0  573
9월     NaN  777
10월    NaN  821

이미 존재하는 데이터프레임의 열 순서를 바꾸려면 아래처럼 열을 리스트로 지정하고 객체로 넘겨주면 간단합니다. 

In [64]:
dataframe4_test = dataframe4[['딸기', '포도', '배', '사과', '복숭아']]
dataframe4_test

딸기   포도    배   사과    복숭아
4월   756.0  402  102  332   32.0
5월   741.0  497   99  392   70.0
6월   794.0  306   80  391   26.0
7월   772.0  681   30  295  154.0
8월   703.0  573  143  374  201.0
9월     NaN  777   26  333    NaN
10월    NaN  821   21  282    NaN

특정 열의 특정 값을 두 가지 형식으로 인덱싱 하겠습니다. '딸기' 열의 '5월' 값과 '9월' 값입니다.

In [65]:
dataframe4['딸기'][['5월', '9월']]

5월    741.0
9월      NaN
Name: 딸기, dtype: float64

In [66]:
dataframe4['딸기'][[1, 5]]

5월    741.0
9월      NaN
Name: 딸기, dtype: float64

두 가지 형식으로 '딸기' 열의 '5월'부터 '9월'까지 슬라이싱 하겠습니다.

In [67]:
dataframe4['딸기']['5월':'9월']

5월    741.0
6월    794.0
7월    772.0
8월    703.0
9월      NaN
Name: 딸기, dtype: float64

In [68]:
dataframe4['딸기'][1:6]

5월    741.0
6월    794.0
7월    772.0
8월    703.0
9월      NaN
Name: 딸기, dtype: float64

## **2.4. 데이터 합치기**

먼저 데이터프레임의 아래로 데이터를 붙이겠습니다. 사용할 함수는 `append()`입니다. 먼저 `dataframe5`를 생성하고, `dataframe4`의 아래에 붙이겠습니다.

In [69]:
dataframe4

배   사과   포도     딸기    복숭아
4월   102  332  402  756.0   32.0
5월    99  392  497  741.0   70.0
6월    80  391  306  794.0   26.0
7월    30  295  681  772.0  154.0
8월   143  374  573  703.0  201.0
9월    26  333  777    NaN    NaN
10월   21  282  821    NaN    NaN

In [70]:
dataframe5 = pd.DataFrame({'배':[30, 40],
                           '사과': [300, 400],
                           '포도': [200, 300],
                           '딸기': [100, 150],
                           '복숭아': [200, 240]})
dataframe5

배   사과   포도   딸기  복숭아
0  30  300  200  100  200
1  40  400  300  150  240

In [71]:
dataframe4.append(dataframe5)

배   사과   포도     딸기    복숭아
4월   102  332  402  756.0   32.0
5월    99  392  497  741.0   70.0
6월    80  391  306  794.0   26.0
7월    30  295  681  772.0  154.0
8월   143  374  573  703.0  201.0
9월    26  333  777    NaN    NaN
10월   21  282  821    NaN    NaN
0     30  300  200  100.0  200.0
1     40  400  300  150.0  240.0

`append()` 함수의 `ignore_index` 매개변수에 `True` 인자를 지정하면 인덱스가 순서대로 통합됩니다.

In [72]:
dataframe4.append(dataframe5, ignore_index=True)

배   사과   포도     딸기    복숭아
0  102  332  402  756.0   32.0
1   99  392  497  741.0   70.0
2   80  391  306  794.0   26.0
3   30  295  681  772.0  154.0
4  143  374  573  703.0  201.0
5   26  333  777    NaN    NaN
6   21  282  821    NaN    NaN
7   30  300  200  100.0  200.0
8   40  400  300  150.0  240.0

인덱스가 0부터 오름차순으로 부여됐지만 기존에 지정했던 'n월' 형식은 초기화됐습니다.  

만약 모든 열의 데이터를 합치지 않는다면 나머지 열의 데이터는 모두 `Nan`으로 표시됩니다.

In [73]:
dataframe6 = pd.DataFrame({'배': [10, 20]})
dataframe4.append(dataframe6, ignore_index=True)

배     사과     포도     딸기    복숭아
0  102  332.0  402.0  756.0   32.0
1   99  392.0  497.0  741.0   70.0
2   80  391.0  306.0  794.0   26.0
3   30  295.0  681.0  772.0  154.0
4  143  374.0  573.0  703.0  201.0
5   26  333.0  777.0    NaN    NaN
6   21  282.0  821.0    NaN    NaN
7   10    NaN    NaN    NaN    NaN
8   20    NaN    NaN    NaN    NaN

이제는 `join()` 함수를 사용하여 데이터프레임을 오른쪽으로 붙이겠습니다. 새로운 열을 가진 데이터프레임 `dataframe7`을 만들고 `dataframe4`의 오른쪽에 붙이겠습니다.

In [74]:
dataframe7 = pd.DataFrame({'바나나': [350, 240, 360, 380]})
dataframe7

바나나
0  350
1  240
2  360
3  380

In [75]:
dataframe4.join(dataframe7)

배   사과   포도     딸기    복숭아  바나나
4월   102  332  402  756.0   32.0  NaN
5월    99  392  497  741.0   70.0  NaN
6월    80  391  306  794.0   26.0  NaN
7월    30  295  681  772.0  154.0  NaN
8월   143  374  573  703.0  201.0  NaN
9월    26  333  777    NaN    NaN  NaN
10월   21  282  821    NaN    NaN  NaN

`join()` 함수는 인덱스가 일치하지 않으면 새로운 열을 통합할 수 없습니다. 인덱스가 일치하는 `dataframe8`을 만들어서 합치겠습니다.

In [76]:
dataframe8 = dataframe4.append(dataframe6, ignore_index=True)
dataframe8

배     사과     포도     딸기    복숭아
0  102  332.0  402.0  756.0   32.0
1   99  392.0  497.0  741.0   70.0
2   80  391.0  306.0  794.0   26.0
3   30  295.0  681.0  772.0  154.0
4  143  374.0  573.0  703.0  201.0
5   26  333.0  777.0    NaN    NaN
6   21  282.0  821.0    NaN    NaN
7   10    NaN    NaN    NaN    NaN
8   20    NaN    NaN    NaN    NaN

In [77]:
dataframe8.join(dataframe7)

배     사과     포도     딸기    복숭아    바나나
0  102  332.0  402.0  756.0   32.0  350.0
1   99  392.0  497.0  741.0   70.0  240.0
2   80  391.0  306.0  794.0   26.0  360.0
3   30  295.0  681.0  772.0  154.0  380.0
4  143  374.0  573.0  703.0  201.0    NaN
5   26  333.0  777.0    NaN    NaN    NaN
6   21  282.0  821.0    NaN    NaN    NaN
7   10    NaN    NaN    NaN    NaN    NaN
8   20    NaN    NaN    NaN    NaN    NaN

인덱스가 동일한 숫자에 맞춰서 바나나열이 추가됐습니다. 아래 데이터는 공백이므로 `NaN`으로 처리됐습니다. 다만 기존 데이터프레임의 인덱스를 유지하면서 데이터를 붙이고 싶으면 `index` 매개변수에 같은 인덱스를 지정하면 됩니다.

먼저 `dataframe4`를 띄우겠습니다.

In [78]:
dataframe4

배   사과   포도     딸기    복숭아
4월   102  332  402  756.0   32.0
5월    99  392  497  741.0   70.0
6월    80  391  306  794.0   26.0
7월    30  295  681  772.0  154.0
8월   143  374  573  703.0  201.0
9월    26  333  777    NaN    NaN
10월   21  282  821    NaN    NaN

`dataframe4`는 인덱스가 7개입니다. `dataframe10`의 '바나나' 열 데이터는 4개뿐이므로 라벨을 4개만 남겨야 합니다.

In [79]:
index4 = ['5월', '6월', '8월', '10월']
dataframe10 = pd.DataFrame({'바나나': [350, 240, 360, 380]}, index=index4)

이제 둘을 합치겠습니다. 인덱스 라벨이 유지되면서 인덱스 라벨과 일치된 데이터만 추가됩니다.

In [80]:
dataframe4.join(dataframe10)

배   사과   포도     딸기    복숭아    바나나
4월   102  332  402  756.0   32.0    NaN
5월    99  392  497  741.0   70.0  350.0
6월    80  391  306  794.0   26.0  240.0
7월    30  295  681  772.0  154.0    NaN
8월   143  374  573  703.0  201.0  360.0
9월    26  333  777    NaN    NaN    NaN
10월   21  282  821    NaN    NaN  380.0

`merge()` 함수를 사용하면 특정한 열을 기준으로 데이터를 붙일 방향을 설정해서 데이터를 붙일 수 있습니다. 방향 설정은 매개변수 `how`에 지정하며 기본값은 `right`인 오른쪽입니다.

먼저 방향을 설정하지 않고 기본값인 오른쪽으로 데이터를 합치겠습니다. 새로운 데이터프레임인 `dataframe11`을 생성합니다.

In [81]:
dataframe11 = pd.DataFrame({'판매점': ['SKT', 'KT', 'LG'],
                            '휴대폰': [100, 200, 300],
                            '집전화': [10, 20, 30]})
dataframe11

판매점  휴대폰  집전화
0  SKT  100   10
1   KT  200   20
2   LG  300   30

`dataframe11`에 붙일 데이터프레임인 `dateframe12`를 생성하겠습니다.

In [82]:
dataframe12 = pd.DataFrame({'판매점': ['SKT', 'KT', 'LG'],
                            '인터넷': [11, 22, 33]})
dataframe12

판매점  인터넷
0  SKT   11
1   KT   22
2   LG   33

두 데이터프레임을 붙이겠습니다.

In [83]:
dataframe11.merge(dataframe12)

판매점  휴대폰  집전화  인터넷
0  SKT  100   10   11
1   KT  200   20   22
2   LG  300   30   33

위 두 데이터프레임은 '판매점' 열이 동일하여 손쉽게 통합됐습니다. 반대로 특정한 열을 기준으로 데이터의 일부만 공통된다면 `merge()` 함수에 매개변수를 전달해야 합니다. 이에 해당하는 매개변수는 통합하는 방법을 지정하는 `how`와 통합 기준 열을 지정하는 `on`입니다.

아래는 매개변수 `how`에 대한 값 목록입니다.

- `left`: 왼쪽 데이터는 모두 선택하고, 지정한 열의 값에 데이터가 있는 오른쪽 데이터를 선택합니다.

- `right`: 오른쪽 데이터는 모두 선택하고, 지정한 열의 값에 데이터가 있는 왼쪽 데이터를 선택합니다.

- `inner`: 지정한 열을 기준으로 왼쪽과 오른쪽 데이터 중에 공통되는 데이터만 선택합니다. 기본값입니다.

- `outer`: 지정한 열을 기준으로 왼쪽과 오른쪽 데이터 모두를 선택합니다.

매개변수에 대한 예시를 들겠습니다. 새로운 데이터프레임을 생성하겠습니다.

In [84]:
dataframe_seoul = pd.DataFrame({'기준': ['사과', '포도', '오이'],
                               '서울': [1, 2, 3]})
dataframe_seoul

기준  서울
0  사과   1
1  포도   2
2  오이   3

In [85]:
dataframe_gyeonggi = pd.DataFrame({'기준': ['사과', '포도', '가지'],
                                '경기': [7, 8, 9]})
dataframe_gyeonggi

기준  경기
0  사과   7
1  포도   8
2  가지   9

먼저 `left`를 전달하겠습니다. 코드에서 왼쪽에 위치한 '서울' 데이터프레임을 모두 가져오고, 그 데이터프레임의 '기준' 값과 일치하는 '경기' 데이터프레임의 값을 합칩니다. '경기' 데이터프레임의 '기준' 열에는 '오이' 값이 없으므로 'NaN'으로 표시됩니다.

In [86]:
dataframe_seoul.merge(dataframe_gyeonggi, how='left', on='기준')

기준  서울   경기
0  사과   1  7.0
1  포도   2  8.0
2  오이   3  NaN

`right`를 전달하겠습니다. 코드에서 오른쪽에 위치한 '경기' 데이터프레임을 모두 가져오고, 그 데이터프레임의 '기준' 값과 일치하는 '서울' 데이터프레임의 값을 합칩니다. '서울' 데이터프레임의 '기준' 열에는 '가지' 값이 없으므로 'NaN'으로 표시됩니다.

In [87]:
dataframe_seoul.merge(dataframe_gyeonggi, how='right', on='기준')

기준   서울  경기
0  사과  1.0   7
1  포도  2.0   8
2  가지  NaN   9

`inner`를 전달하겠습니다. 두 데이터프레임의 '기준' 값 중에 공통되는 값만 표시합니다. '사과'와 '포도'만 공통됩니다.

In [88]:
dataframe_seoul.merge(dataframe_gyeonggi, how='inner', on='기준')

기준  서울  경기
0  사과   1   7
1  포도   2   8

`outer`를 전달하겠습니다. 두 데이터프레임의 '기준' 값을 모두 합칩니다.

In [89]:
dataframe_seoul.merge(dataframe_gyeonggi, how='outer', on='기준')

기준   서울   경기
0  사과  1.0  7.0
1  포도  2.0  8.0
2  오이  3.0  NaN
3  가지  NaN  9.0

## **2.5. 데이터 파일 읽기**

`read_csv()` 함수를 사용하면 표 데이터인 csv 파일을 읽어올 수 있습니다. csv란 comma-separated values의 약자이고, 데이터 필드가 쉼표(,)로 구분된 파일을 의미합니다. 확장자는 `.csv`이며 텍스트로만 구성된 파일입니다. 물론 `sep` 매개변수에 구분자 값을 지정하면 쉼표가 아닌 다른 구분자로 구분된 데이터도 읽어올 수 있습니다. 먼저 구글 드라이브를 임포트 하고 아래에서 예시로 설명하겠습니다.

In [90]:
from google.colab import drive
drive.mount('/content/gdrive/')

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).


In [91]:
cd /content/gdrive/MyDrive/Python_for_Data_Analytics_Science

/content/gdrive/MyDrive/Python_for_Data_Analytics_Science


csv 파일을 생성하겠습니다.

In [92]:
%%writefile /content/gdrive/MyDrive/Python_for_Data_Analytics_Science/test_csv.csv

월, 사과, 배, 포도, 바나나
1, 15, 26, 32, 76
2, 30, 20, 36, 47
3, 42, 91, 25, 63
4, 29, 84, 37, 72
5, 53, 67, 74, 23

Overwriting /content/gdrive/MyDrive/Python_for_Data_Analytics_Science/test_csv.csv


csv 파일을 읽겠습니다.

In [93]:
pd.read_csv('/content/gdrive/MyDrive/Python_for_Data_Analytics_Science/test_csv.csv')

월   사과   배   포도   바나나
0  1   15  26   32    76
1  2   30  20   36    47
2  3   42  91   25    63
3  4   29  84   37    72
4  5   53  67   74    23

참고로 윈도우 메모장에서 파일을 생성하면 인코딩 형식은 'cp949'입니다. 반면에 파이썬으로 텍스트 파일을 생성하면 문자 인코딩 형식은 'utf-8'이 됩니다. 인코딩 형식이 다르므로 `read_csv()` 메서드의 `encoding` 매개변수에 인코딩 형식을 인자값으로 넘겨줘야 텍스트 파일을 제대로 읽을 수 있습니다.

만약 구분자가 공백이면 매개변수를 `sep=' '`로 지정합니다.

In [95]:
%%writefile /content/gdrive/MyDrive/Python_for_Data_Analytics_Science/test_csv1.csv

월 사과 배 포도 바나나
1 15 26 32 76
2 30 20 36 47
3 42 91 25 63
4 29 84 37 72
5 53 67 74 23

Writing /content/gdrive/MyDrive/Python_for_Data_Analytics_Science/test_csv1.csv


In [97]:
pd.read_csv('/content/gdrive/MyDrive/Python_for_Data_Analytics_Science/test_csv1.csv', sep=' ')

월  사과   배  포도  바나나
0  1  15  26  32   76
1  2  30  20  36   47
2  3  42  91  25   63
3  4  29  84  37   72
4  5  53  67  74   23

데이터를 읽을 때 열 하나를 인덱스로 지정할 수 있습니다. 매개변수 `index_col`에 특정 열을 인자로 전달하겠습니다.

In [98]:
pd.read_csv('/content/gdrive/MyDrive/Python_for_Data_Analytics_Science/test_csv1.csv', sep=' ', index_col='월')

사과   배  포도  바나나
월                 
1  15  26  32   76
2  30  20  36   47
3  42  91  25   63
4  29  84  37   72
5  53  67  74   23

## **2.6. 데이터 파일 쓰기**

`to_csv()` 메서드를 사용하면 데이터프레임을 텍스트 파일로 생성할 수 있습니다.

먼저 위 데이터를 데이터프레임으로 생성하겠습니다.

In [103]:
dataframe_to_csv = pd.DataFrame({'사과': [15, 30, 42, 29, 53],
                                 '배': [26, 20, 91, 84, 67],
                                 '포도': [32, 36, 25, 37, 74],
                                 '바나나': [76, 47, 63, 72, 23]}, index=[1, 2, 3, 4, 5])
dataframe_to_csv.index.name = '월'
dataframe_to_csv

사과   배  포도  바나나
월                 
1  15  26  32   76
2  30  20  36   47
3  42  91  25   63
4  29  84  37   72
5  53  67  74   23

바나나 열의 오른쪽에 모든 과일의 월 평균판매량 열을 추가하겠습니다. 

In [117]:
sum_sale = dataframe_to_csv['사과'] + dataframe_to_csv['배'] + dataframe_to_csv['포도'] + dataframe_to_csv['바나나']
mean_sale = sum_sale/4
mean_sale

dataframe_to_csv['평균 판매량'] = mean_sale
dataframe_to_csv

사과   배  포도  바나나  평균 판매량
월                         
1  15  26  32   76   37.25
2  30  20  36   47   33.25
3  42  91  25   63   55.25
4  29  84  37   72   55.50
5  53  67  74   23   54.25

생성한 데이터프레임을 텍스트 파일로 저장하겠습니다. 구분자를 기본값인 쉼표가 아닌 공백으로 지정하고 문자는 `cp949`로 지정하겠습니다.

In [120]:
dataframe_to_csv.to_csv('/content/gdrive/MyDrive/Python_for_Data_Analytics_Science/to_csv1.csv', 
                        sep=' ', encoding='cp949')

# **추가할 내용을 구상 중입니다.**