<a href="https://colab.research.google.com/github/LeeSeungwon89/Python_for_Data_Analytics_Science/blob/main/2.%20%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%A5%BC%20%EB%8B%A4%EB%A3%A8%EA%B8%B0%20%EC%9C%84%ED%95%9C%20%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%ED%8C%A8%ED%82%A4%EC%A7%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Numpy**

넘파이는 데이터를 다루는 데 필수적인 패키지입니다. 과학적인 연산을 빠르고 쉽게 해줍니다. 아래에는 몇 가지 내용만 정리하겠습니다. 이외 구체적인 정보는 [넘파이 홈페이지](https://www.numpy.org)에 정리되어 있습니다.

## **1.1. 배열 만들기**

배열을 만드는 방법은 여러가지가 있습니다. 

아래에서 예시로 설명하겠습니다. 먼저 시퀀스 데이터를 인자로 받고 배열 객체를 생성하는 방법입니다.

In [6]:
import numpy as np

# 튜플도 가능하지만 주로 리스트를 사용합니다.
# 정수만으로 구성된 리스트입니다.
list_int = [0, 1, 2, 3, 4]
np_int = np.array(list_int)
print(np_int)
np_int

[0 1 2 3 4]


array([0, 1, 2, 3, 4])

배열 속성을 확인합니다.

In [14]:
np_int.dtype

dtype('int64')

정수와 실수를 함께 포함시켜서 만들겠습니다. 이렇게 하면 모든 원소를 실수 형태로 출력합니다.

In [15]:
list_combi = [0, 1.2, 3, 4.56, 7]
np_combi = np.array(list_combi)
np_combi

array([0.  , 1.2 , 3.  , 4.56, 7.  ])

배열 속성을 확인합니다.

In [13]:
np_combi.dtype

dtype('float64')

문자를 함께 포함시키겠습니다. 이렇게 하면 모든 원소를 문자로 간주하게 됩니다.

In [11]:
list_str = [0, '일', 2.3, '사']
np_str = np.array(list_str)
np_str

array(['0', '일', '2.3', '사'], dtype='<U21')

배열 속성을 확인합니다. '<U21'는 유니코드 문자열을 의미합니다. 여기서 '21'은 문자 수가 최대 21개라는 점을 의미합니다.

In [16]:
np_str.dtype

dtype('<U21')

`np.array(리스트)` 형식으로 바로 배열 객체를 만들 수도 있습니다.

In [17]:
np_direct1 = np.array([0, 1, 2, 3, 4])
np_direct1

array([0, 1, 2, 3, 4])

In [19]:
np_direct2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
np_direct2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

범위를 지정해서 배열을 만들 수 있습니다. 파이썬 `range()` 함수와 유사하게 넘파이는 `arange()` 함수를 사용합니다.

In [20]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [21]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`arange()` 함수에 `reshape()` 함수를 더하면 행렬 형태로 변경할 수 있습니다.

In [27]:
np.arange(8).reshape(4, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

배열 형태를 확인하겠습니다. 참고로 1차원 배열은 `(원소 개수,)` 형태로 출력됩니다. 예컨대 원소 개수가 34개라면 `(34,)`로 출력됩니다.

In [28]:
np_reshape = np.arange(8).reshape(4, 2)
np_reshape.shape

(4, 2)

`linspace()` 함수를 사용하면 지정한 데이터 개수에 따라 배열을 만듭니다. 0부터 10까지 20개만큼 데이터를 만들겠습니다.

In [35]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

`zeros()` 함수는 0으로만 이루어진 배열을 만듭니다. `ones()` 함수는 1로만 이루어진 배열을 만듭니다. 사용법은 동일합니다.

In [42]:
zeros_1 = np.zeros(5)
print(zeros_1)
print()
# 2차원 배열을 만들려면 괄호로 한 번 더 묶어야 합니다.
ones_2 = np.ones((5, 2))
print(ones_2)

[0. 0. 0. 0. 0.]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


`eye()` 함수는 단위행렬(Identity matrix)을 만듭니다. 

In [43]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

`rand()` 함수와 `randint()` 함수는 각각 실수 난수와 정수 난수를 생성합니다. 

In [69]:
rand1 = np.random.rand()
print(rand1)
print()
# 2 x 4 배열을 생성합니다.
rand2 = np.random.rand(2, 4)
print(rand2)
print()
# 3차원 배열을 생성합니다.
rand3 = np.random.rand(2, 4, 6)
print(rand3)

0.19884466579499527

[[0.65642217 0.18369044 0.60376356 0.01738299]
 [0.89602552 0.97285124 0.70748589 0.06241116]]

[[[0.76690136 0.77666579 0.04057743 0.75138673 0.14797778 0.78578186]
  [0.21363732 0.94565255 0.91026044 0.55706883 0.93916511 0.83596065]
  [0.47787946 0.33234798 0.44733385 0.78318784 0.54010196 0.66069829]
  [0.31374326 0.65819112 0.1753725  0.28124383 0.89746533 0.50984071]]

 [[0.63820608 0.8299006  0.16534547 0.74723002 0.23724899 0.19903946]
  [0.24458734 0.47748053 0.29101498 0.05998284 0.35000939 0.38461406]
  [0.31296745 0.75577557 0.63172866 0.66319998 0.58316396 0.10401554]
  [0.43270658 0.5321851  0.04041258 0.03075386 0.2558525  0.12999194]]]


In [77]:
# 5~10 사이의 정수 난수를 생성합니다.
randint1 = np.random.randint(5, 10)
print(randint1)
print()
# 0 ~ 10 사이의 정수 난수를 2 x 5 배열로 생성합니다.
randint2 = np.random.randint(10, size=(2, 5))
print(randint2)
print()
# 0 ~ 12 사이의 정수 난수를 3차원 배열로 생성합니다.
randint3 = np.random.randint(12, size=(3, 2, 5))
print(randint3)

7

[[4 8 8 3 2]
 [8 8 5 7 4]]

[[[ 0  3 10 10 10]
  [ 7  1  5  8 11]]

 [[ 0  1 11 10  7]
  [ 1  0  1 10 11]]

 [[ 7  4 11 10 10]
  [ 6  5  1  6  8]]]


## **1.2. 배열 타입 변환하기**

넘파이 데이터의 형식은 아래와 같습니다.

- 'i': 기호를 가진 정수(signed integer)

- 'u': 기호가 없는 정수(unsigned integer)

- 'f': 실수(floating-point)

- 'c': 복소수(complex-floating point)

- 'b': 불(bool)

- 'O': 파이썬 객체(object)

- 'U': 유니코드(unicode)

- 'S' or 'a': 바이트 문자열(string)

- 'M': 날짜(datetime)

`astype()` 함수를 사용하여 배열 타입(형)을 바꿀 수 있습니다. `astype()` 함수에 인자로 `int`(정수형), `float`(실수형), `str`(문자형) 중에 하나를 넣고 배열 형을 변환합니다.

In [96]:
np_str = np.array(['0.1', '2', '3.45', '6.7'])
print(f'np_str의 타입은 {np_str.dtype}')
# 실수 타입으로 변환합니다.
np_astype_float = np_str.astype(float)
print(f'np_astype_float의 타입은 {np_astype_float.dtype}')
# 정수 타입으로 변환합니다. 
np_astype_int = np_astype_float.astype(int)
print(f'np_astype_int의 타입은 {np_astype_int.dtype}, 원소는 {np_astype_int}')

np_str의 타입은 <U4
np_astype_float의 타입은 float64
np_astype_int의 타입은 int64, 원소는 [0 2 3 6]


## **1.3. 배열 연산하기**

통계에 활용하는 여러 함수가 있습니다. 아래는 함수 목록입니다.

- `sum()`: 합계

- `mean()`: 평균

- `std()`: 표준 편차

- `var()`: 분산

- `max()`: 최댓값

- `min()`: 최솟값

- `cumsum()`: 누적합

- `cumprod()`: 누적곱

배열을 생성하고 예시를 들겠습니다.

In [109]:
arr_cal = np.arange(7)
print(f'arr_cal: {arr_cal}')
print(f'sum(): {arr_cal.sum()}')
print(f'mean(): {arr_cal.mean()}')
print(f'std(): {arr_cal.std()}')
print(f'var(): {arr_cal.var()}')
print(f'max(): {arr_cal.max()}')
print(f'min(): {arr_cal.min()}')
print(f'cumsum(): {arr_cal.cumsum()}')
print(f'sumprod(): {arr_cal.cumprod()}')

arr_cal: [0 1 2 3 4 5 6]
sum(): 21
mean(): 3.0
std(): 2.0
var(): 4.0
max(): 6
min(): 0
cumsum(): [ 0  1  3  6 10 15 21]
sumprod(): [0 0 0 0 0 0 0]


선형 대수를 위한 행렬 연산을 수행하는 함수도 있습니다. 아래는 함수 목록입니다.

- `dot()`: 행렬곱(matrix product)
- `transpose()`: 전치 행렬(transpose matrix)
- `linalg.inv()`: 역행렬(inverse matrix)
- `linalg.det()`: 행렬식(determinant)

2차원 배열을 생성하고 함수를 사용하겠습니다.

In [132]:
matrix1 = np.array([0, 1, 2, 3]).reshape(2, 2)
matrix2 = np.array([1, 2, 3, 4]).reshape(2, 2)
print('matrix1:')
print(matrix1)
print('matrix2:')
print(matrix2)

matrix1:
[[0 1]
 [2 3]]
matrix2:
[[1 2]
 [3 4]]


`dot()` 함수로 행렬곱을 구하겠습니다. 두 형식으로 쓸 수 있습니다.

In [136]:
print(matrix1.dot(matrix2))
print(np.dot(matrix1, matrix2))

[[ 3  4]
 [11 16]]
[[ 3  4]
 [11 16]]


`transpose()` 함수로 전치 행렬을 만들겠습니다. 두 형식으로 쓸 수 있습니다.

In [139]:
print('matrix1:')
print(matrix1)
print('transpose():')
print(matrix1.transpose())
print(np.transpose(matrix1))

matrix1:
[[0 1]
 [2 3]]
transpose():
[[0 2]
 [1 3]]
[[0 2]
 [1 3]]


`linalg.inv()` 함수로 역행렬을 구하겠습니다.

In [133]:
print('matrix1:')
print(matrix1)
print('np.linalg.inv(matrix1)')
print(np.linalg.inv(matrix1))

matrix1:
[[0 1]
 [2 3]]
np.linalg.inv(matrix1)
[[-1.5  0.5]
 [ 1.   0. ]]


`linalg.det()` 함수로 행렬식을 구하겠습니다.

In [140]:
print('matrix1:')
print(matrix1)
print('np.linalg.det(matrix1)')
print(np.linalg.det(matrix1))

matrix1:
[[0 1]
 [2 3]]
np.linalg.det(matrix1)
-2.0


## **1.4. 배열 인덱싱 하기**

## **1.5. 배열 슬라이싱 하기**

# **2. Pandas**