<a href="https://colab.research.google.com/github/LeeSeungwon89/Python_for_Data_Analytics_Science/blob/main/%EB%B3%B4%EA%B0%95.%20%EB%84%98%ED%8C%8C%EC%9D%B4%20%EB%B0%8F%20%ED%8C%90%EB%8B%A4%EC%8A%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. 넘파이**

## **1.1. ndarray의 데이터 타입**

다른 데이터 유형이 섞인 리스트를 `ndarray`로 바꾸면 크기가 더 큰 데이터 타입으로 형 변환을 수행합니다.

In [25]:
import numpy as np

In [26]:
a = [1, 2, 3.0]
array1 = np.array(a)

print(array1)
print(array1.dtype)

[1. 2. 3.]
float64


In [27]:
b = [1, 2, 'three']
array2 = np.array(b)
 
print(array2)
print(array2.dtype)

['1' '2' 'three']
<U21


`astype()` 메서드로 `ndarray`의 데이터 타입을 바꿀 수 있습니다. 데이터 타입을 변경하는 이유는 대용량 데이터의 `ndarray`를 생성할 때 필요한 메모리를 줄이기 위함입니다. 데이터 타입이 `float`인 경우 `int`로도 충분하다면 `int`로 형 변환을 시도할 수 있습니다. 

In [28]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')

print(array_float)
print(array_float.dtype)

[1. 2. 3.]
float64


## **1.2. 행렬 정렬**

`np.sort()`처럼 `sort()` 메서드를 호출하거나 `ndarray.sort()`처럼 행렬에 바로 `sort()` 메서드를 호출하여 행렬 정렬을 수행할 수 있습니다. 다만 두 가지 방식에는 차이점이 있습니다. 먼저 `np.sort()` 방식을 구현해보겠습니다.

In [29]:
array_example = np.array([6, 2, 4, 1])
print('원래 행렬:', array_example)
print()

array_sorted = np.sort(array_example)
print('정렬한 행렬:', array_sorted)
print('원래 행렬:', array_example)

원래 행렬: [6 2 4 1]

정렬한 행렬: [1 2 4 6]
원래 행렬: [6 2 4 1]


이 방식은 원래 행렬인 `array_example`을 그대로 유지한 채 따로 행렬 정렬을 수행합니다.

반면 `ndarray.sort()` 방식은 원래 행렬 자체를 정렬합니다. 구현해보겠습니다.

In [30]:
array_example = np.array([6, 2, 4, 1])
print('원래 행렬:', array_example)
print()

array_sorted = array_example.sort()
print('정렬한 행렬:', array_sorted)
print('원래 행렬:', array_example)

원래 행렬: [6 2 4 1]

정렬한 행렬: None
원래 행렬: [1 2 4 6]


정렬한 행렬 객체인 `array_sorted`는 `None`이 되고 원래 행렬인 `array_example` 객체 자체를 영구적으로 정렬하여 바꿨습니다.

넘파이의 `sort()` 메서드는 기본적으로 오름차순 정렬을 수행합니다. 내림차순으로 정렬하려면 메서드 뒤에 `[::-1]` 형식을 취합니다. 구현해보겠습니다.

In [31]:
array_example = np.array([6, 2, 4, 1])
array_sorted = np.sort(array_example)[::-1]

print('정렬한 행렬:', array_sorted)

정렬한 행렬: [6 4 2 1]


행 방향(`axis=0`), 열 방향(`axis=1`)으로 정렬할 수도 있습니다. `sort()` 메서드에 매개변수를 `axis=0` 또는 `axis=1`로 지정하면 됩니다. 먼저 `axis=0`으로 지정해보겠습니다.

In [35]:
array_2d_example = np.array([[6, 2],
                             [4, 1]])
array_sorted = np.sort(array_2d_example, axis=0)

print('정렬한 행렬:\n', array_sorted)

정렬한 행렬:
 [[4 1]
 [6 2]]


이번엔 `axis=1`로 지정해보겠습니다.

In [36]:
array_2d_example = np.array([[6, 2],
                             [4, 1]])
array_sorted = np.sort(array_2d_example, axis=1)

print('정렬한 행렬:\n', array_sorted)

정렬한 행렬:
 [[2 6]
 [1 4]]


행렬을 정렬했을 때 원래 행렬의 원소에 대한 인덱스를 넘파이의 `argsort()` 메서드를 호출하여 얻을 수 있습니다. 확인해보겠습니다. 

In [38]:
array_example = np.array([6, 2, 4, 1])
array_sorted_indices = np.argsort(array_example)

print(array_sorted_indices)
print(type(array_sorted_indices))

[3 1 2 0]
<class 'numpy.ndarray'>


내림차순으로 정렬하려면 메서드 뒤에 `[::-1]` 형식을 취합니다. 구현해보겠습니다. 

In [39]:
array_example = np.array([6, 2, 4, 1])
array_sorted_indices = np.argsort(array_example)[::-1]

print(array_sorted_indices)
print(type(array_sorted_indices))

[0 2 1 3]
<class 'numpy.ndarray'>


# **2. 판다스**


---

**이어서 보강하겠습니다.**

---

